import os
import re
import json
import asyncio
from pathlib import Path
from asyncio import create_subprocess_exec
from asyncio.subprocess import PIPE
from aiofiles.os import path as aiopath

from bot import LOGGER, user_data
from bot.core.config_manager import BinConfig
from bot.helper.ext_utils.bot_utils import decode_output
from bot.helper.ext_utils.ffmpeg_utils import _create_memory_aware_subprocess

# --- Constants and Templates ---

# Fixed resolution for intro sub so it doesn't zoom with video
INTRO_SUB_RES_X = 1920
INTRO_SUB_RES_Y = 1080

ASS_HEADER_TEMPLATE = """[Script Info]
; Script generated by MH Intro Subtitle Generator
ScriptType: v4.00+
PlayResX: {playresx}
PlayResY: {playresy}
ScaledBorderAndShadow: no
WrapStyle: 2
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Intro,{font},{size},&H00FFFFFF,&H0000FFFF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,3,0,{align},60,60,{margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

ALIGN_MAP = {"bottom": 2, "center": 5, "top": 8}
DEFAULT_COLOR = "#0000FF"
TEXT_FORMATS = ["ass", "ssa", "srt", "vtt", "webvtt", "sami", "sub", "ttml"]
BITMAP_FORMATS = ["hdmv_pgs_subtitle", "dvd_subtitle", "dvb_subtitle"]

# Allowed styles and positions for intro subtitles
ALLOWED_STYLES = {"typing", "fade", "static", "auto"}
ALLOWED_POSITIONS = {"top", "bottom", "middle", "center", "centre"}


def HEX_TO_ASS(h):
    """Convert hex color to ASS subtitle format (BGR order)"""
    if re.match(r"^#?[0-9A-Fa-f]{6}$", h):
        # Remove # if present
        hex_color = h[1:] if h.startswith("#") else h
        # Convert RGB to BGR for ASS format
        return f"&H00{hex_color[4:6]}{hex_color[2:4]}{hex_color[0:2]}"
    else:
        # Use DEFAULT_COLOR instead of defaulting to white
        default_hex = (
            DEFAULT_COLOR[1:] if DEFAULT_COLOR.startswith("#") else DEFAULT_COLOR
        )
        return f"&H00{default_hex[4:6]}{default_hex[2:4]}{default_hex[0:2]}"


COLOR_NAME_MAP = {
    "red": "#FF0000",
    "blue": "#0000FF",
    "green": "#00FF00",
    "yellow": "#FFFF00",
    "white": "#FFFFFF",
    "black": "#000000",
    "orange": "#FFA500",
    "purple": "#800080",
    "pink": "#FF69B4",
    "cyan": "#00FFFF",
    "magenta": "#FF00FF",
    "lime": "#32CD32",
    "gold": "#FFD700",
    "silver": "#C0C0C0",
    "brown": "#A52A2A",
    "gray": "#808080",
    "grey": "#808080",
    "violet": "#8A2BE2",
    "indigo": "#4B0082",
    "navy": "#000080",
    "teal": "#008080",
    "olive": "#808000",
    "maroon": "#800000",
    "aqua": "#00FFFF",
    "fuchsia": "#FF00FF",
    "coral": "#FF7F50",
    "salmon": "#FA8072",
    "crimson": "#DC143C",
    "darkred": "#8B0000",
    "darkblue": "#00008B",
    "darkgreen": "#006400",
    "lightblue": "#ADD8E6",
    "lightgreen": "#90EE90",
    "lightgray": "#D3D3D3",
    "lightgrey": "#D3D3D3",
}


DEFAULT_COLORS = ["#FF0000", "#0000FF", "#00FF00", "#FFA500", "#800080", "#000000"]


def get_available_colors():
    """Return a list of available color names."""
    return list(COLOR_NAME_MAP.keys())


def get_color_examples():
    """Return formatted examples of color usage."""
    basic_colors = ["red", "blue", "green", "yellow", "white"]
    return f"Examples: {' | '.join(basic_colors)} or {' | '.join([COLOR_NAME_MAP[c] for c in basic_colors[:3]])}"


def validate_color_input(colors_raw: str):
    """Validate and return parsed colors from user input.

    Args:
        colors_raw (str): Raw color input string (space or pipe-separated).

    Returns:
        Tuple[List[str], List[str]]: Valid colors and invalid colors.
    """
    colors, invalid_colors = [], []
    if colors_raw:
        sep = "|" if "|" in colors_raw else " "
        for c in colors_raw.split(sep):
            c = c.strip().lower()
            if not c:
                continue
            # Check if it's a color name first
            if c in COLOR_NAME_MAP:
                colors.append(COLOR_NAME_MAP[c])
            # Check if it's a hex color with #
            elif (
                c.startswith("#") and len(c) == 7 and re.match(r"^#[0-9A-Fa-f]{6}$", c)
            ):
                colors.append(c)
            # Check if it's a hex color without #
            elif re.match(r"^[0-9A-Fa-f]{6}$", c):
                colors.append("#" + c)
            else:
                invalid_colors.append(c)
    return colors, invalid_colors


def _format_time(ms: int, sub_format: str) -> str:
    if ms < 0:
        ms = 0
    total_seconds, m_seconds = ms // 1000, ms % 1000
    h = total_seconds // 3600
    m = (total_seconds % 3600) // 60
    s = total_seconds % 60
    if sub_format == "srt":
        return f"{h:02d}:{m:02d}:{s:02d},{m_seconds:03d}"
    elif sub_format in ["vtt", "webvtt", "sami", "ttml"]:
        return f"{h:02d}:{m:02d}:{s:02d}.{m_seconds:03d}"
    elif sub_format == "ass":
        return f"{h}:{m:02d}:{s:02d}.{m_seconds // 10:02d}"
    else:
        return f"{h:02d}:{m:02d}:{s:02d}.{m_seconds:03d}"


def _parse_time(time_str: str) -> int:
    if not time_str:
        return 0
    time_str = time_str.replace(",", ".")
    parts = time_str.split(":")
    if len(parts) != 3:
        return 0
    try:
        h, m = int(parts[0]), int(parts[1])
        s_parts = parts[2].split(".")
        s = int(s_parts[0])
        ms = int(s_parts[1].ljust(3, "0")[:3]) if len(s_parts) > 1 else 0
        return (h * 3600 + m * 60 + s) * 1000 + ms
    except (ValueError, IndexError):
        return 0


def _shift_timestamps(content: str, offset_ms: int, sub_format: str) -> str:
    if not content or offset_ms <= 0:
        return content
    if sub_format == "ass":
        ass_pattern = re.compile(
            r"^(Dialogue: .*?,)(\d:\d{2}:\d{2}\.\d{2})(,)(\d:\d{2}:\d{2}\.\d{2})(,.*)",
            flags=re.MULTILINE,
        )

        def repl(match):
            start_ms = _parse_time(match.group(2)) + offset_ms
            end_ms = _parse_time(match.group(4)) + offset_ms
            start = _format_time(start_ms, "ass")
            end = _format_time(end_ms, "ass")
            return f"{match.group(1)}{start}{match.group(3)}{end}{match.group(5)}"

        return ass_pattern.sub(repl, content)
    time_pattern = re.compile(r"(\d{1,2}:\d{2}:\d{2}[,.]\d{2,3})")

    def replacer(m):
        original_ms = _parse_time(m.group(1))
        new_ms = original_ms + offset_ms
        return _format_time(new_ms, sub_format)

    return time_pattern.sub(replacer, content)


def _renumber_srt(content: str, add: int) -> str:
    if add <= 0 or not content:
        return content
    lines = content.splitlines()
    result_lines = []
    for line in lines:
        stripped_line = line.strip()
        if stripped_line.isdigit():
            result_lines.append(str(int(stripped_line) + add))
        else:
            result_lines.append(line)
    return "\n".join(result_lines)


# --- Subtitle Detection and Extraction ---
async def check_embedded_subtitles(video_path: str):
    if not os.path.exists(video_path):
        LOGGER.error(f"Video file not found: {video_path}")
        return False, None, None
    cmd = [
        BinConfig.FFPROBE_NAME,
        "-v",
        "quiet",
        "-print_format",
        "json",
        "-show_streams",
        video_path,
    ]
    try:
        process = await _create_memory_aware_subprocess(
            *cmd, stdout=PIPE, stderr=PIPE, max_retries=2, wait_for_resources=False
        )

        if not process:
            LOGGER.error(f"Failed to create subprocess for stream check: {video_path}")
            return False, None, None

        stdout, stderr = await process.communicate()
        if process.returncode != 0:
            LOGGER.error(f"ffprobe failed for stream check: {decode_output(stderr)}")
            return False, None, None
        data = json.loads(decode_output(stdout, "response"))
        all_streams = data.get("streams", [])
        sub_streams = [s for s in all_streams if s.get("codec_type") == "subtitle"]
        if sub_streams:
            first_sub = sub_streams[0]
            LOGGER.info(
                f"Found embedded subtitle: Codec '{first_sub.get('codec_name')}', Index {first_sub.get('index')}"
            )
            return True, first_sub, all_streams
        return False, None, all_streams
    except json.JSONDecodeError as e:
        LOGGER.error(f"JSON decode error: {e}")
        return False, None, None
    except Exception as e:
        LOGGER.error(f"Error checking embedded subtitles: {e}")
        return False, None, None


async def extract_subtitle(video_path: str, stream_info: dict, output_dir: Path):
    """Extract subtitle with improved error handling and validation."""
    from ..ext_utils.video_process_utils import temp_file, generate_unique_filename

    if not stream_info:
        LOGGER.error("No stream information provided")
        return None, ""

    stream_index = stream_info.get("index")
    if stream_index is None:
        LOGGER.error("Stream index not found in stream info")
        return None, ""

    codec_name = (stream_info.get("codec_name") or "").lower()
    is_bitmap = codec_name in BITMAP_FORMATS
    sub_format = "srt" if is_bitmap else codec_name

    # Validate and normalize subtitle format
    if sub_format not in TEXT_FORMATS:
        sub_format = "srt"
    if sub_format == "webvtt":
        sub_format = "vtt"

    if is_bitmap:
        LOGGER.warning(
            f"Bitmap subtitle format '{codec_name}' detected; cannot extract as text. "
            "Skipping extraction and falling back to generating new intro subtitle."
        )
        return None, ""

    # Generate safe subtitle title
    sub_title = stream_info.get("tags", {}).get("title")
    if not sub_title:
        sub_title = f"extracted_sub_{stream_info.get('index', 'NA')}"
    else:
        # Sanitize title for filename
        sub_title = "".join(
            c for c in sub_title if c.isalnum() or c in (" ", "_", "-")
        ).strip()
        if not sub_title:
            sub_title = f"extracted_sub_{stream_info.get('index', 'NA')}"

    # Generate unique output path to avoid conflicts
    base_output = output_dir / f"{sub_title}.{sub_format}"
    output_path = Path(generate_unique_filename(str(base_output)))

    # Build FFmpeg extraction command
    cmd = [
        BinConfig.FFMPEG_NAME,
        "-hide_banner",
        "-y",
        "-loglevel",
        "error",
        "-analyzeduration",
        "10M",
        "-probesize",
        "50M",
        "-i",
        video_path,
        "-map",
        f"0:{stream_index}",
        "-c",
        sub_format if sub_format != "vtt" else "webvtt",
        str(output_path),
    ]

    LOGGER.debug(
        f"Extracting subtitle stream {stream_index} ({codec_name}) to {sub_format}..."
    )

    try:
        # Use timeout to prevent hanging
        proc = await _create_memory_aware_subprocess(
            *cmd, stdout=PIPE, stderr=PIPE, max_retries=2, wait_for_resources=False
        )

        if not proc:
            LOGGER.error(
                f"Failed to create subprocess for subtitle extraction: {video_path}"
            )
            return None, None

        try:
            _, stderr = await asyncio.wait_for(
                proc.communicate(), timeout=300
            )  # 5 minute timeout
        except asyncio.TimeoutError:
            proc.kill()
            await proc.wait()
            LOGGER.error(f"Subtitle extraction timed out for stream {stream_index}")
            return None, ""

        if proc.returncode != 0:
            stderr_str = stderr.decode(errors="ignore")
            LOGGER.error(
                f"Subtitle extraction failed for stream {stream_index}: {stderr_str}"
            )
            return None, ""

        # Validate output file
        if not await aiopath.isfile(output_path):
            LOGGER.error(
                f"Subtitle extraction failed: Output file not created: {output_path}"
            )
            return None, ""

        file_size = await aiopath.getsize(output_path)
        if file_size == 0:
            LOGGER.error(
                f"Subtitle extraction failed: Output file is empty: {output_path}"
            )
            # Clean up empty file
            try:
                await aiopath.unlink(output_path)
            except Exception:
                pass
            return None, ""

        LOGGER.debug(
            f"Successfully extracted subtitle to: {output_path} ({file_size} bytes)"
        )
        return output_path, sub_format

    except Exception as e:
        LOGGER.error(
            f"Unexpected error during subtitle extraction from stream {stream_index}: {e}"
        )
        # Clean up partial file if it exists
        try:
            if await aiopath.isfile(output_path):
                await aiopath.unlink(output_path)
        except Exception:
            pass
        return None, ""


def _get_user_settings(user_id: int, overrides: dict | None = None) -> dict:
    user_dict = user_data.get(user_id, {})
    ovr = overrides or {}
    colors_raw = ovr.get("colors") or user_dict.get("INTRO_SUBTITLE_COLORS") or ""
    colors, _ = validate_color_input(colors_raw)
    mono_color = colors[0] if colors else DEFAULT_COLOR
    try:
        font_size = int(
            ovr.get("font_size") or user_dict.get("INTRO_SUBTITLE_FONT_SIZE") or 48
        )
        font_size = max(12, min(200, font_size))
    except (ValueError, TypeError):
        font_size = 48
    try:
        char_ms = int(
            ovr.get("char_ms") or user_dict.get("INTRO_SUBTITLE_CHAR_MS") or 300
        )
        char_ms = max(50, min(2000, char_ms))
    except (ValueError, TypeError):
        char_ms = 300

    # Get duration override if specified
    duration_ms = None
    if overrides:
        duration_ms = overrides.get("duration")
    if duration_ms is None and user_dict:
        duration_ms = user_dict.get("INTRO_SUBTITLE_DURATION")

    # Convert to integer if present
    if duration_ms is not None:
        try:
            duration_ms = int(duration_ms)
            if duration_ms <= 0:
                duration_ms = None
        except (ValueError, TypeError):
            duration_ms = None

    settings = {
        "text": ovr.get("text")
        or user_dict.get("INTRO_SUBTITLE_TEXT")
        or "encoded by MH",
        "style": (
            ovr.get("style") or user_dict.get("INTRO_SUBTITLE_STYLE") or "typing"
        ).lower(),
        "font_path": ovr.get("font_path")
        or user_dict.get("INTRO_SUBTITLE_FONT_PATH")
        or "",
        "font_size": font_size,
        "position": (
            ovr.get("position") or user_dict.get("INTRO_SUBTITLE_POSITION") or "bottom"
        ).lower(),
        "char_ms": char_ms,
        "color": mono_color,
        "duration": duration_ms,  # New duration field
    }

    # Normalize and validate style
    if settings["style"] not in ALLOWED_STYLES:
        settings["style"] = "typing"  # Safe default

    # Normalize and validate position (handle center/centre equivalence)
    if settings["position"] == "centre":
        settings["position"] = "center"
    if settings["position"] not in ALLOWED_POSITIONS:
        settings["position"] = "bottom"  # Safe default

    return settings


def _is_customized_subtitle(user_id: int, overrides: dict | None = None) -> bool:
    """
    Determine if subtitle has customization that requires ASS format.

    Returns True if any customization is applied (styling, effects, positioning, etc.)
    Returns False for plain subtitles (which can use SRT format)
    """
    settings = _get_user_settings(user_id, overrides)

    # Check for animation/effect styles (requires ASS)
    style = settings.get("style", "typing")
    if style in ["typing", "fade"]:
        return True

    # "auto" will be resolved to typing/fade later, so consider it customized
    if style == "auto":
        return True

    # For "static" style, check if there are other customizations
    # If static with no other customization, return False to use SRT

    # Check for non-default positioning (requires ASS for precise control)
    position = settings.get("position", "bottom")
    if position != "bottom":
        return True

    # Check for custom font (requires ASS)
    font_path = settings.get("font_path", "")
    if font_path:
        return True

    # Check for non-default font size (requires ASS for precise control)
    font_size = settings.get("font_size", 48)
    if font_size != 48:
        return True

    # Check for custom colors (requires ASS)
    color = settings.get("color", DEFAULT_COLOR)
    if color != DEFAULT_COLOR:
        return True

    # Duration override with static style can use SRT
    # Only consider customization for non-static styles
    duration = settings.get("duration")
    if duration is not None and style != "static":
        return True

    # If we reach here, it's a plain subtitle (static with defaults) - use SRT
    return False


async def _generate_intro_lines(
    user_id: int, sub_format: str, overrides: dict | None = None
):
    s = _get_user_settings(user_id, overrides)
    text = s["text"]
    style = s["style"]
    color = s["color"]
    per_char_ms = max(50, int(s["char_ms"]))
    duration_override = s["duration"]  # New duration field
    if not text:
        text = "encoded by MH"

    # Handle "auto" style - resolve to fade for ASS/SSA, typing for SRT/VTT
    if style == "auto":
        if sub_format in ["ass", "ssa"]:
            style = "fade"
        else:  # SRT, VTT, etc.
            style = "typing"

    if style == "typing":
        if sub_format == "ass":
            tagged_text = ""
            fade_dur = 1
            for i, char in enumerate(text):
                appear_ms = i * per_char_ms
                tag = f"{{\\alpha&HFF\\t({appear_ms},{appear_ms + fade_dur},\\alpha&H00)}}"
                tagged_text += tag + char
            # Use duration override if set, otherwise calculate from characters
            if duration_override:
                total_ms = duration_override
            else:
                total_ms = len(text) * per_char_ms + 2000
            end = _format_time(total_ms, "ass")
            block = f"Dialogue: 0,0:00:00.00,{end},Intro,,0,0,0,,{{\\c{HEX_TO_ASS(color)}}}{tagged_text}"
            return block, total_ms, 1
        else:
            cues = []
            n = 0
            for i in range(1, len(text) + 1):
                n += 1
                start_ms = (i - 1) * per_char_ms
                if i == len(text):
                    if duration_override:
                        end_ms = duration_override
                    else:
                        end_ms = start_ms + per_char_ms + 2000
                else:
                    end_ms = start_ms + per_char_ms
                chunk = text[:i]
                start_time = _format_time(start_ms, "srt")
                end_time = _format_time(end_ms, "srt")
                cues.extend(
                    [
                        f"{n}",
                        f"{start_time} --> {end_time}",
                        chunk,
                        "",
                    ]
                )
            # Use duration override for total calculation if set
            if duration_override:
                total_ms = duration_override
            else:
                total_ms = len(text) * per_char_ms + 2000
            return "\n".join(cues).rstrip(), total_ms, n
    elif style == "fade" and sub_format == "ass":
        # Use duration override if set, otherwise calculate from characters
        if duration_override:
            total_ms = duration_override
        else:
            total_ms = max(2000, per_char_ms * len(text))
        end = _format_time(total_ms, "ass")
        block = f"Dialogue: 0,0:00:00.00,{end},Intro,,0,0,0,,{{\\fad(300,500)}}{{\\c{HEX_TO_ASS(color)}}}{text}"
        return block, total_ms, 1
    else:
        # Use duration override if set, otherwise calculate from characters
        if duration_override:
            total_ms = duration_override
        else:
            total_ms = max(1500, per_char_ms * len(text))
        if sub_format == "ass":
            end = _format_time(total_ms, "ass")
            block = f"Dialogue: 0,0:00:00.00,{end},Intro,,0,0,0,,{{\\c{HEX_TO_ASS(color)}}}{text}"
            return block, total_ms, 1
        else:
            end = _format_time(total_ms, "srt")
            content = text
            block = f"1\n00:00:00,000 --> {end}\n{content}"
            return block, total_ms, 1


async def insert_intro_into_subtitle(
    sub_path: Path, sub_format: str, user_id: int, overrides: dict | None = None
):
    """Insert intro into subtitle with improved error handling and cleanup."""
    from ..ext_utils.video_process_utils import temp_file, generate_unique_filename

    try:
        if not sub_path or not sub_path.exists():
            LOGGER.error(f"Subtitle file not found: {sub_path}")
            return None

        # Validate subtitle format
        if sub_format not in TEXT_FORMATS:
            LOGGER.error(f"Unsupported subtitle format: {sub_format}")
            return None

        # Generate intro content
        intro_block, intro_ms, intro_cues = await _generate_intro_lines(
            user_id, sub_format, overrides
        )
        if not intro_block:
            LOGGER.error("Failed to generate intro block - no intro content created")
            return None

        # Read and validate original subtitle file
        try:
            original = sub_path.read_text(encoding="utf-8", errors="ignore")
        except Exception as e:
            LOGGER.error(f"Failed to read subtitle file {sub_path}: {e}")
            return None

        if not original.strip():
            LOGGER.error(f"Original subtitle file is empty: {sub_path}")
            return None

        # Shift timestamps in original content
        try:
            shifted = _shift_timestamps(original, intro_ms + 500, sub_format)
        except Exception as e:
            LOGGER.error(f"Failed to shift timestamps in subtitle: {e}")
            return None

        # Build modified content based on format
        try:
            if sub_format in ["vtt", "webvtt"]:
                # Handle WebVTT format
                header_match = re.search(r"^(WEBVTT[^\n]*\n)", shifted, re.MULTILINE)
                if header_match:
                    header = header_match.group(1)
                    body = shifted[len(header) :].strip()
                    modified = f"{header}\n{intro_block}\n\n{body}"
                else:
                    modified = f"WEBVTT\n\n{intro_block}\n\n{shifted}"
            elif sub_format == "ass":
                # Handle ASS format
                event_header = "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
                if event_header in shifted:
                    modified = shifted.replace(
                        event_header, f"{event_header}\n{intro_block}", 1
                    )
                else:
                    # Fallback: append to end
                    modified = shifted + "\n" + intro_block
            else:
                # Handle SRT and other numbered formats
                shifted_bumped = _renumber_srt(shifted, intro_cues)
                modified = intro_block.strip() + "\n\n" + shifted_bumped.strip()
                if not modified.endswith("\n"):
                    modified += "\n"
        except Exception as e:
            LOGGER.error(f"Failed to build modified subtitle content: {e}")
            return None

        # Generate unique output path to avoid conflicts
        base_output = sub_path.with_name(f"modified_{sub_path.name}")
        out_path = Path(generate_unique_filename(str(base_output)))

        # Write modified content with error handling
        try:
            out_path.write_text(modified, encoding="utf-8")
        except Exception as e:
            LOGGER.error(f"Failed to write modified subtitle to {out_path}: {e}")
            return None

        # Validate output file
        try:
            if not out_path.exists() or out_path.stat().st_size == 0:
                LOGGER.error(f"Generated subtitle file is empty or missing: {out_path}")
                return None
        except Exception as e:
            LOGGER.error(f"Failed to validate output file {out_path}: {e}")
            return None

        LOGGER.debug(f"Successfully generated modified subtitle at {out_path}")
        return out_path

    except Exception as e:
        LOGGER.error(
            f"Unexpected error inserting intro into subtitle: {e}", exc_info=True
        )
        return None


def build_intro_replace_cmd(
    video_path: str, mod_sub_path: Path, sub_to_replace: dict, all_streams: list
):
    if not os.path.exists(video_path) or not mod_sub_path.exists():
        return None, None
    p = Path(video_path)
    out_path = str(p.with_name(f"{p.stem}_intro.mkv"))
    cmd = [
        BinConfig.FFMPEG_NAME,
        "-hide_banner",
        "-y",
        "-loglevel",
        "error",
        "-i",
        video_path,
        "-i",
        str(mod_sub_path),
    ]
    map_args, metadata_args, output_sub_index = [], [], 0
    for stream in all_streams:
        if stream["index"] == sub_to_replace["index"]:
            map_args.extend(["-map", "1:0"])
            tags = stream.get("tags", {}) or {}
            if tags.get("language"):
                metadata_args.extend(
                    [
                        f"-metadata:s:s:{output_sub_index}",
                        f"language={tags['language']}",
                    ]
                )
            if tags.get("title"):
                metadata_args.extend(
                    [f"-metadata:s:s:{output_sub_index}", f"title={tags['title']}"]
                )
            metadata_args.extend(
                [f"-disposition:s:{output_sub_index}", "default+forced"]
            )
            output_sub_index += 1
        else:
            map_args.extend(["-map", f"0:{stream['index']}"])
            if stream.get("codec_type") == "subtitle":
                output_sub_index += 1
    cmd.extend(map_args)
    cmd.extend(["-c", "copy"])
    cmd.extend(metadata_args)
    cmd.extend(["-progress", "pipe:1"])
    cmd.append(out_path)
    return cmd, out_path


async def _get_video_resolution(video_path: str):
    """Get video resolution from file."""
    try:
        cmd = [
            BinConfig.FFPROBE_NAME,
            "-v",
            "quiet",
            "-print_format",
            "json",
            "-show_streams",
            video_path,
        ]
        proc = await _create_memory_aware_subprocess(
            *cmd, stdout=PIPE, stderr=PIPE, max_retries=1, wait_for_resources=False
        )

        if not proc:
            LOGGER.error(
                f"Failed to create subprocess for video resolution check: {video_path}"
            )
            return 720, 1280  # Default resolution

        out, _ = await proc.communicate()
        if proc.returncode == 0:
            data = json.loads(out)
            for s in data.get("streams", []):
                if s.get("codec_type") == "video":
                    w = s.get("width")
                    h = s.get("height")
                    if w and h and int(w) > 0 and int(h) > 0:
                        return int(w), int(h)
    except Exception as e:
        LOGGER.debug(f"Could not get video resolution: {e}")
    return INTRO_SUB_RES_X, INTRO_SUB_RES_Y


async def generate_intro_ass(
    user_id: int, video_path: str, overrides: dict | None = None
):
    """Generate a standalone ASS file using a fixed resolution so intro sub doesn't zoom."""
    try:
        settings = _get_user_settings(user_id, overrides)
        font_path = settings["font_path"]
        font_size = settings["font_size"]
        position = settings["position"]
        # Always use fixed resolution for intro sub so it doesn't zoom
        width, height = INTRO_SUB_RES_X, INTRO_SUB_RES_Y
        intro_events, _, _ = await _generate_intro_lines(user_id, "ass", overrides)
        font_name = "Arial"
        if font_path and os.path.exists(font_path):
            font_name = os.path.basename(font_path)
        ass_content = (
            ASS_HEADER_TEMPLATE.format(
                playresx=width,
                playresy=height,
                font=font_name,
                size=font_size,
                align=ALIGN_MAP.get(position, 2),
                margin_v=80 if position == "bottom" else 60,
            )
            + intro_events
            + "\n"
        )
        ass_path = Path(video_path).parent / "intro_generated.ass"
        ass_path.write_text(ass_content, encoding="utf-8")
        LOGGER.debug(f"Generated intro-only ASS for fallback at {ass_path}")
        return ass_path
    except Exception as e:
        LOGGER.error(f"Failed writing intro-only ASS: {e}")
        return None


def build_intro_mux_cmd(
    video_path: str,
    ass_path: Path,
    user_id: int,
    all_streams: list,
    overrides: dict | None = None,
):
    """Build intro subtitle mux command with improved stream index calculation."""
    if not os.path.exists(video_path) or not ass_path.exists():
        return None, None

    from ..ext_utils.video_process_utils import generate_unique_filename

    # Generate unique output filename to avoid conflicts
    p = Path(video_path)
    out_path = generate_unique_filename(
        str(p.with_stem(f"{p.stem}_intro")), extension=".mkv"
    )

    # Robust stream index calculation handling gaps in subtitle streams
    subtitle_streams = [s for s in all_streams if s.get("codec_type") == "subtitle"]
    existing_sub_count = len(subtitle_streams)

    # Calculate the next available subtitle index
    # Account for potential gaps in stream indices
    used_indices = {s.get("index", -1) for s in subtitle_streams}
    max_index = max(used_indices) if used_indices else -1
    new_sub_index = existing_sub_count  # Output stream index

    try:
        cmd = [
            BinConfig.FFMPEG_NAME,
            "-hide_banner",
            "-y",
            "-loglevel",
            "error",
            "-i",
            video_path,
            "-i",
            str(ass_path),
            "-map",
            "0",  # Map all streams from input 0 (video file)
            "-map",
            "1",  # Map subtitle from input 1 (ass file)
            "-c",
            "copy",  # Copy all streams without re-encoding
            "-disposition:s",
            "0",  # Clear all subtitle dispositions first
            f"-disposition:s:{new_sub_index}",
            "default+forced",  # Set new intro subtitle as default
            f"-metadata:s:s:{new_sub_index}",
            "language=eng",
            f"-metadata:s:s:{new_sub_index}",
            "title=Intro",
            "-progress",
            "pipe:1",
            out_path,
        ]

        LOGGER.debug(
            f"Built intro mux command for {existing_sub_count} existing subs, new index {new_sub_index}"
        )
        return cmd, out_path

    except Exception as e:
        LOGGER.error(f"Error building intro mux command: {e}")
        return None, None


async def convert_subtitle_to_srt(input_sub_path: Path):
    """Convert subtitle to SRT format with enhanced error handling."""
    from ..ext_utils.video_process_utils import generate_unique_filename

    try:
        if not input_sub_path or not input_sub_path.exists():
            LOGGER.error(f"Input subtitle file not found: {input_sub_path}")
            return None

        # Check if input is already SRT
        if input_sub_path.suffix.lower() == ".srt":
            LOGGER.debug("Input is already SRT format")
            return input_sub_path

        # Generate unique output path
        base_output = input_sub_path.with_suffix(".srt")
        out_path = Path(generate_unique_filename(str(base_output)))

        # Build conversion command with timeout and better parameters
        cmd = [
            BinConfig.FFMPEG_NAME,
            "-hide_banner",
            "-y",
            "-loglevel",
            "error",
            "-i",
            str(input_sub_path),
            "-c:s",
            "srt",
            str(out_path),
        ]

        LOGGER.debug(f"Converting subtitle {input_sub_path} to SRT format...")

        # Run with timeout to prevent hanging
        try:
            proc = await _create_memory_aware_subprocess(
                *cmd, stdout=PIPE, stderr=PIPE, max_retries=2, wait_for_resources=True
            )

            if not proc:
                LOGGER.error(
                    f"Failed to create subprocess for subtitle conversion: {input_sub_path}"
                )
                return None

            stdout, stderr = await asyncio.wait_for(
                proc.communicate(), timeout=120
            )  # 2 minute timeout
        except asyncio.TimeoutError:
            proc.kill()
            await proc.wait()
            LOGGER.error(f"SRT conversion timed out for {input_sub_path}")
            return None

        if proc.returncode == 0:
            # Validate output file
            if await aiopath.isfile(out_path):
                file_size = await aiopath.getsize(out_path)
                if file_size > 0:
                    LOGGER.debug(
                        f"Successfully converted to SRT: {out_path} ({file_size} bytes)"
                    )
                    return out_path
                else:
                    LOGGER.error("Converted SRT file is empty")
                    # Clean up empty file
                    try:
                        await aiopath.unlink(out_path)
                    except Exception:
                        pass
            else:
                LOGGER.error("Converted SRT file was not created")
        else:
            stderr_str = stderr.decode(errors="ignore")
            LOGGER.error(f"SRT conversion failed: {stderr_str}")

    except Exception as e:
        LOGGER.error(f"Error converting subtitle to SRT: {e}")
        # Clean up partial file if it exists
        try:
            if "out_path" in locals() and await aiopath.isfile(out_path):
                await aiopath.unlink(out_path)
        except Exception:
            pass

    return None


async def generate_intro_srt(
    user_id: int, video_path: str, overrides: dict | None = None
):
    try:
        srt_block, _, _ = await _generate_intro_lines(user_id, "srt", overrides)
        if not srt_block:
            LOGGER.error("Failed to generate SRT intro block")
            return None
        srt_path = Path(video_path).parent / "intro_generated.srt"
        if not srt_block.endswith("\n"):
            srt_block += "\n"
        srt_path.write_text(srt_block, encoding="utf-8")
        LOGGER.debug(f"Generated intro-only SRT for fallback at {srt_path}")
        return srt_path
    except Exception as e:
        LOGGER.error(f"Failed writing intro-only SRT: {e}")
        return None


def test_color_generation(colors_input: str, text: str = "Test Colors") -> str:
    """Generate a test ASS content to verify color application."""
    colors, invalid_colors = validate_color_input(colors_input)
    if not colors:
        colors = DEFAULT_COLORS

    # Simple test generation - just show colors without karaoke
    syllables = []
    for i, ch in enumerate(text):
        if ch == " ":
            syllables.append(" ")
            continue
        colour = colors[i % len(colors)]
        ass_color = HEX_TO_ASS(colour)
        syllables.append(f"{{\\c{ass_color}}}{ch}")

    line = "".join(syllables)

    # Create a simple test ASS file content
    ass_header = ASS_HEADER_TEMPLATE.format(
        playresx=INTRO_SUB_RES_X,
        playresy=INTRO_SUB_RES_Y,
        font="Arial",
        size=48,
        align=2,
        margin_v=80,
    )

    # Add both static and typing test lines
    test_events = [
        f"Dialogue: 0,0:00:00.00,0:00:03.00,Intro,,0,0,0,,{{\\c{HEX_TO_ASS(colors[0])}}}Static: {text}",
        f"Dialogue: 0,0:00:04.00,0:00:08.00,Intro,,0,0,0,,Multi-color: {line}",
    ]

    ass_content = ass_header + "\n".join(test_events) + "\n"

    result = f"Input: '{colors_input}'\n"
    result += f"Colors parsed: {colors}\n"
    if invalid_colors:
        result += f"Invalid colors ignored: {invalid_colors}\n"
    result += f"\nGenerated test ASS content:\n{ass_content}"

    return result


def diagnose_intro_subtitle_settings(user_id: int) -> str:
    """Diagnose intro subtitle settings for a user"""
    user_dict = user_data.get(user_id, {})

    diagnosis = f"🔍 **Intro Subtitle Diagnosis for User {user_id}**\n\n"

    # Check if feature is enabled
    enabled = user_dict.get("INTRO_SUBTITLE_ENABLED", False)
    diagnosis += f"✅ **Enabled**: {enabled}\n"
    if not enabled:
        diagnosis += "❌ **Issue**: Intro subtitle is not enabled. Enable it in settings first.\n"
        return diagnosis

    # Check text
    text = user_dict.get("INTRO_SUBTITLE_TEXT", "")
    diagnosis += f"📝 **Text**: '{text or 'Default: Encoded by BLX'}'\n"

    # Check style
    style = user_dict.get("INTRO_SUBTITLE_STYLE", "")
    diagnosis += f"🎨 **Style**: '{style or 'Default: typing'}'\n"

    # Check colors
    colors_raw = user_dict.get("INTRO_SUBTITLE_COLORS", "")
    diagnosis += f"🌈 **Colors Input**: '{colors_raw or 'Not set - using defaults'}'\n"

    if colors_raw:
        colors, invalid = validate_color_input(colors_raw)
        diagnosis += f"✅ **Valid Colors**: {colors}\n"
        if invalid:
            diagnosis += f"❌ **Invalid Colors**: {invalid}\n"
    else:
        diagnosis += f"📋 **Default Colors**: {DEFAULT_COLORS}\n"

    # Check other settings
    font_size = user_dict.get("INTRO_SUBTITLE_FONT_SIZE", "")
    position = user_dict.get("INTRO_SUBTITLE_POSITION", "")
    char_ms = user_dict.get("INTRO_SUBTITLE_CHAR_MS", "")

    diagnosis += f"📏 **Font Size**: {font_size or 'Default: 48'}\n"
    diagnosis += f"📍 **Position**: {position or 'Default: bottom'}\n"
    diagnosis += f"⏱️ **Char Timing**: {char_ms or 'Default: 300ms'}\n"

    # Provide recommendations
    diagnosis += "\n🔧 **Recommendations**:\n"
    if not colors_raw:
        diagnosis += (
            "• Set custom colors: `red|blue|green` or `#FF0000|#00FF00|#0000FF`\n"
        )
    if style.lower() not in ["typing", "fade", "static"]:
        diagnosis += "• Use valid style: typing, fade, or static\n"

    return diagnosis
